### ISSUE TITLE
Blocking unitframes ?

### ISSUE THREAD

**Issue by soxa83** [lenonk/ElvUI_SpellBinder#12]
Hi, 

First of all nice add on for replacing clique but i have 1 question ?
Is there somewhere an option where you can blacklist unitframes like player frame and target frame so you can use only spells on party/raid frames ?

thx in advance !

**Comment by lenonk** [comment]
No, I'm sorry, there isn't.  Unfortunately, I no longer have a WoW account, so I'm not maintaining this addon anymore.  If anyone else wants to take over maintenance, I'd have no issues with that though.

**Comment by soxa83** [comment]
Hi,

Ah ok sorry to hear that but its ok :)

thx anyways
