### ISSUE TITLE
AceGUI 3.0

### ISSUE THREAD

**Issue by themadtux** [lenonk/ElvUI_SpellBinder#2]
Getting the following LUA Warning.. when I login 

```
Message: ...ElvUI_SpellBinder\Libraries\AceGUI-3.0-SharedMediaWidgets\prototypes.lua:4: unexpected symbol near ']'
Time: Sun Oct 21 16:52:31 2018
Count: 1
Stack: ...ElvUI_SpellBinder\Libraries\AceGUI-3.0-SharedMediaWidgets\prototypes.lua:4: unexpected symbol near ']'

Locals: 
```
and 

```
Message: ...ElvUI_SpellBinder\Libraries\AceGUI-3.0-SharedMediaWidgets\prototypes.lua:4: unexpected symbol near ']'
Time: Sun Oct 21 16:52:45 2018
Count: 5
```

Thanks...

**Comment by lenonk** [comment]
Looks like the same issue as #3.

There's no hint as to what's causing this in the backtrace.  Can you send me your bindings so I can try to reproduce?

Thanks!

**Comment by lenonk** [comment]
Also, please, send any information about *when* this happens.  Is it on login?  Is it when any certain thing happens?

**Comment by lenonk** [comment]
There's no information in that stack trace that gives me any hint as to what's going on. Can you please send your list of bindings?

Also, please, send any information about when this happens. Is it on login? Is it when any certain thing happens?

Thanks!

**Comment by lenonk** [comment]
Please see this thread:
https://github.com/lenonk/ElvUI_SpellBinder/issues/3

It appears this is not a bug in my code, but some sort of corruption during download or maybe just with 1.0.5 package.  I'm not sure.  Either way, the code is correct in the repo, so I'm not sure what to do about this.
